name: Staging Build and Deploy

on: [push]

env:
  CF_API: ${{ secrets.CF_API }}
  CF_ORG: ${{ secrets.CF_ORG }}
  CF_SPACE: ${{ secrets.CF_SPACE }}
  CF_USERNAME: ${{ secrets.CF_USERNAME }}
  CF_PASSWORD: ${{ secrets.CF_PASSWORD }}

jobs:
  # build and deploy staging
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # setup cf cli with bg plugin and login
      - uses: jvalkeal/setup-cf-cli@v0
        with:
          version: 6.51.0
          plugin-repo: https://plugins.cloudfoundry.org
          plugin-id: blue-green-deploy
          login: true

      # do site build and prepare for cf push
      - name: Yarn build
        run: |
          yarn install
          yarn run fix
          yarn build
          yarn run prepare-cf-push

      # do cf blue/green deploy
      - name: CF Staging Deploy
        run: cf blue-green-deploy dataflow-website-staging -f manifest-local.yml --smoke-test ./blue-green-smoke.sh --delete-old-apps

  # check links jobs, runs if build was ok
  links:
    name: Check links
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn Install
        run: |
          yarn install

      # can't run with parallel jobs as gh is rate limiting
      # so need to run via sequential steps and allow to continue
      # even if step fails to sweep through all
      - name: Linkinator (current)
        run: |
          yarn install
          yarn run linkinator https://dataflow-staging.cfapps.io
      - name: Linkinator (2.2.x)
        if: success() || failure()
        run: |
          yarn install
          yarn run linkinator https://dataflow-staging.cfapps.io/docs/2.2.x
