name: Staging Check Links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  links:
    # prevent run on forks for cron
    if: (github.event_name == 'schedule' && github.repository == 'spring-io/dataflow.spring.io') || (github.event_name != 'schedule')
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn Install
        run: |
          yarn install

      # can't run with parallel jobs as gh is rate limiting
      # so need to run via sequential steps and allow to continue
      # even if step fails to sweep through all
      - name: Linkinator (current)
        run: |
          yarn run linkinator https://dataflow-staging.cfapps.io --concurrency 1 --silent
      - name: Linkinator (2.7.0.SNAPSHOT)
        if: success() || failure()
        run: |
          yarn run linkinator https://dataflow-staging.cfapps.io/docs/2.7.0.SNAPSHOT --concurrency 1 --silent
      - name: Linkinator (2.5.x)
        if: success() || failure()
        run: |
          yarn run linkinator https://dataflow-staging.cfapps.io/docs/2.5.x --concurrency 1 --silent
      - name: Linkinator (2.4.x)
        if: success() || failure()
        run: |
          yarn run linkinator https://dataflow-staging.cfapps.io/docs/2.4.x --concurrency 1 --silent
      - name: Linkinator (2.3.x)
        if: success() || failure()
        run: |
          yarn run linkinator https://dataflow-staging.cfapps.io/docs/2.3.x --concurrency 1 --silent
      - name: Linkinator (2.2.x)
        if: success() || failure()
        run: |
          yarn run linkinator https://dataflow-staging.cfapps.io/docs/2.2.x --concurrency 1 --silent
